name: CI

on:
  push:
    branches: ['**']

jobs:
  check-formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run prettier
        run: yarn prettier -c .

      - name: Run eslint
        run: yarn lint

  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

      - name: Run Component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: yarn cypress run-ct
          browser: chrome
